### ISSUE TITLE
ps4 controller won't connect with switch 

### ISSUE THREAD

**Issue by MEATYER** [jakibaki/hid-mitm#14]
so I did everything for this to work and what do I get? NOTHING BUT A PS4 CONTROLLER THAT IS CONNECTED WITH MY PC INSTEAD OF SWITCH I tried this so many times im about to give up and just buy the adaptor I don't know how ds4 windows would work I don't know what people are meaning by 

"the white box must be on the top and the top only"
everything must be closed (already did that) 
 
but I don't know what the white box must be on the top and the top only 

so if someone can fix my issue thank you so much 

-+

**Comment by friedkeenan** [comment]
This is the guy who tried to use hid-mitm without having CFW @jakibaki

**Comment by MEATYER** [comment]
Dude I fixed it shut the fuck up @friedkeenan

**Comment by friedkeenan** [comment]
Lol I'm just letting him know he can close this (or you could)

**Comment by MEATYER** [comment]
Like I said, I fixed it. So you can stop being a dick @friedkeenan

**Comment by jakibaki** [comment]
Thanks @friedkeenan 

Closing now.
