### ISSUE TITLE
Uncompatible with Kosmos 12.1.0 & AMS 0.8.8

### ISSUE THREAD

**Issue by vector9a02** [jakibaki/hid-mitm#17]
Cause switch-boot-logo freeze on Kosmos 12.1.0 / AMS 0.8.8 / Hekate 4.10 /OFW 8.0.0 (clean install on fat32 sd). Works fine on OFW 7.0.X

**Comment by Krazer89** [comment]
Works on AMS 0.8.8 (FW 8.0.0) with libstratosphere commit Atmosphere-NX/libstratosphere@163d9259a365c3a89c1a837b28e7609d45795e40

**Comment by jakibaki** [comment]
Fixed with 299d1b1c2842e205f1662c2fa623d8996c7e0988, many thanks @Krazer89
