### ISSUE TITLE
8.1.0 compat

### ISSUE THREAD

**Issue by d3st1nyh4x** [jakibaki/hid-mitm#26]
enabling hid-mitm on 8.1.0 causes the switch to hang on final boot logo (Official ns one)

**Comment by fabrebatalla18** [comment]
Please, fix for 8.1.0

**Comment by smogt** [comment]
I have the same problem, stuck on Nintendo switch boot logo.

**Comment by friedkeenan** [comment]
Should be as simple as compiling with a later libstratosphere

**Comment by Xirious** [comment]
Same here. I hope this will be fixed soon.

**Comment by miloazul10** [comment]
Me too, Fantastic HomeBrew, But will be better if works in 8.1.0

**Comment by tgb20** [comment]
@friedkeenan Can you say which version of libstratosphere? I tried compiling with the newest version and the make failed.

**Comment by friedkeenan** [comment]
Probably [this commit](https://github.com/Atmosphere-NX/libstratosphere/commit/7e0ed3b38f437791fdd398c7058c376c9d2a6853)

**Comment by Xirious** [comment]
Anybody been able to fix this by recompiling with libstratosphere?

**Comment by tgb20** [comment]
I rebuilt it using the latest version of libstratosphere and it still freezes on the Nintendo Switch logo. I might have done something wrong but everything seems to have gone through.

**Comment by tgb20** [comment]
A change from my last post. I got the newest version of libstratosphere in the repo, but when building the project it fails to create the exefs.nsp. There are also hundreds of errors while the build is running. This happens whether I run the current version, or the newest version with the new libstratosphere. @friedkeenan If you are able to rebuild it and see if you can get it to work that would be a great help. I am doing this from a Mac and it appears this repo and its build tools were designed to run on Windows.

**Comment by friedkeenan** [comment]
Compiling with the libstratosphere commit I linked and v2.2.0 of libnx (not master) built an exefs nsp, but I'm on 5.1.0 so I can't test to see if it works for 8.1.0.

**Comment by Xirious** [comment]
@friedkeenan

I'm on 8.1.0 and I'd be willing to test (this weekend) I'm just not sure how?

**Comment by tgb20** [comment]
Works on 8.1.0. I didn't have my devkitPro updated. Used the commit above and the newest version of devkitPro.

**Comment by friedkeenan** [comment]
might be worth it to make a PR then that updates libstratopshere to that commit @tgb20

**Comment by MarcioBarrientos** [comment]
@friedkeenan @tgb20 Hi, I build the hid-mitm with the commit above and it works, I did test it with 8.1.0 and PS4 controller.
[https://gofile.io/?c=XpBldb](url)

**Comment by miloazul10** [comment]
> @friedkeenan @tgb20 Hi, I build the hid-mitm with the commit above and it works, I did test it with 8.1.0 and PS4 controller (with missing input from O, R and options buttons)
> [https://gofile.io/?c=XpBldb](url)

You are our Hero!, I tested, and Work!, Thank You very much!

**Comment by Xirious** [comment]
This worked for me. 8.1.0 Kosmos + Xbox One BT controller.
