### ISSUE TITLE
reinx

### ISSUE THREAD

**Issue by Aighttttt** [jakibaki/hid-mitm#37]
i know you said reinx isnt supported and prob wont be but could you please make the hid mitm into a kip?

**Comment by friedkeenan** [comment]
It doesn't need to be a kip to work on ReiNX. Just rename the atmosphere directory in the release to reinx. Don't know if it'll work but it won't be because it's not a kip

**Comment by Aighttttt** [comment]
it doesn't work when you change the name thats why i'm asking for a kip
