### ISSUE TITLE
config.ini relocation

### ISSUE THREAD

**Issue by designgears** [jakibaki/hid-mitm#4]
Consider storing config.ini in /config/hid-mitm/config.ini instead of creating yet another folder in root.

**Comment by jakibaki** [comment]
Sorry but I don't see how the `/config` folder would be any more standard than `/modules`.  
I honestly can't think of any homebrew that uses that folder.

`/modules` is the default path used by kosmos so imo it makes sense for it to be like that.

**Comment by designgears** [comment]
Have you heard of nx-hbmenu? or sys-clk?

https://github.com/switchbrew/nx-hbmenu/blob/29caa7688443b18e5f9c5920ae74a577d733990f/common/menu.c#L327

https://github.com/retronx-team/sys-clk/blob/330e378d39f267aa34a693f715b5ee861442f561/src/file_utils.h#L19

**Comment by blawar** [comment]
have you considered using the switch's built in save system for this task?  My goal is to move to the approach, use the system as designed rather than littering the SD card.

**Comment by jakibaki** [comment]
a) reopening since it's apparently not as simple

b) @blawar in this case that would be a bad idea since the config is supposed to be easily user-accessible due to the nature of gamepad-rebinds giving people the ability to shoot themselves in the foot.

**Comment by blawar** [comment]
people shouldn't be editing that stuff by hand, ideally anyway, they should be editing it in a homebrew config app.  No matter what is in that file, it shouldnt prevent a homebrew editor from booting, which could also have an option to restore defaults if the screw it up bad.  People abuse the SD card too much, I am in the process of moving my files to nand as well.

**Comment by WerWolv** [comment]
@blawar Problem being, if you can't access the file because you messed up the controls with the button remapping you're basically fucked. Right now deleting the config file reverts you back. Your way is useful for other homebrew for sure but definitely not for this

**Comment by blawar** [comment]
@WerWolv I think you are confusing the distinction between configuring the app, and actually using it.  If a homebrew app was written to configure it, it would be user friendly and it could also have a button to reset the mapping.  You have the kosmos toolkit, you can use that to edit the button mapps and to reset to default.  The user does not need actual access to the file.  Most switch users are not Linus Torvalds who enjoy editing a text file in vi, quite the opposite.

having your users edit any text files, for any reason, is bad user experience right out of the gate.  I thought the entire point of kosmos was to be user friendly?

**Comment by WerWolv** [comment]
@blawar Let's assume for example the uses messes up the R button configuration. He couldn't even launch the hbmenu anymore without modifying atmosphere's loader.ini config. Being able to just tell the user to take out their SD card and deleting one file sounds much easier to me than telling them to edit loader.ini to open the hbmenu with a different button.

**Comment by ttimasdf** [comment]
@blawar would you write that app for us? It should be bullet-proof that will revert everything back in case the controller is misconfigured and completely nuked, without user actions.
If not, let's get back to the config file.

**Comment by designgears** [comment]
Closing this so people stop posting worthless comments on it.
