### ISSUE TITLE
[REQUEST] Hori Split pad joycons button remap ?!

### ISSUE THREAD

**Issue by xMounirV** [jakibaki/hid-mitm#44]
Hello :) ,

I'm humbly asking if you'd be able to make an update for Firmware 17.0.0
and is it possible to swap B-A buttons for the Hori joycons , they don't support button remaping in the system settings.
I'm certain a lot of people need it.
Thanks in advance !

**Comment by jakibaki** [comment]
Hii this repo is long dead unfortunately ^^’
