### ISSUE TITLE
Implement a deadzone in the clients

### ISSUE THREAD

**Issue by UnicornsOnLSD** [jakibaki/hid-mitm#5]
Since the clients don't have a deadzone, any imperfection in the controller gets detected as movement. This causes the controls to drift. Here's a video: https://streamable.com/crddu

By implementing a configurable deadzone, inaccuracies in the controller would be ignored. Dolphin demonstrates it very well: https://gfycat.com/FarawayDistantIcelandichorse

**Comment by ianisverycool** [comment]
I have the same issue. A temporary solution for this if you're using your PC with dualshock is you can customize the deadzone profile of your controller with DS4Windows, which fixed the issue for me. For xbox if you're using windows 10 you can use the xbox accessories app to customize your controllers deadzone as well, but I have not tried this myself. I imagine it would work though.

**Comment by jakibaki** [comment]
Fixed with 88b308332b67c6e55e6d1e709c58f88e8e5ab6da thanks to @friedkeenan :)

**Comment by friedkeenan** [comment]
Now even further closed with d994c07d356a17ee7a11731c3f377e5c441f1497

**Comment by UnicornsOnLSD** [comment]
Thanks for this, can you send me the Windows client please? Building anything is horrific on Windows and it doesn't help that there aren't any build instructions :p 

@jakibaki
